### ISSUE TITLE
Sugar connection can't be shared for more than one path

### ISSUE THREAD

**Issue by oriolf** [jaracil/nxcli#4]
When a sugar service logs in and pulls on some path, then the service's connection can't be used to push on some other path, even if the login credentials have push permissions on this path. 

The push is rejected with [-32010] Permission denied.

It seems that both server.go and service.go have their own dial, both of which are called when using NewService and service.Serve(), but only one of which has a correct login.

**Comment by rgzr** [comment]
Hi oriolf,

 ¿Which versions are you trying with?

I have tried the following and it works for me with the latest development version of nxcli (and sugar) and version 0.1.1 of nexus. Running the fibsrv sugar example and the following code and doing a task push as root to "test.issue" results in a correct push to "test.sugar.fibsrv.fib" with the same connection used to pull.

`package main

import (
	"time"

	"github.com/jaracil/ei"
	"github.com/jaracil/nxcli/demos/go/sugar"
	. "github.com/jaracil/nxcli/demos/go/sugar/log"
	nexus "github.com/jaracil/nxcli/nxcore"
)

func main() {
	s := sugar.NewService("root:root@localhost", &sugar.ServiceOpts{"test", 4, time.Hour, 12, false})
	s.AddMethod("issue", func(task *nexus.Task) (interface{}, *nexus.JsonRpcErr) {
		res, err := s.GetConn().TaskPush("test.sugar.fibsrv.fib", ei.M{"v":1000, "t": 1}, time.Minute)
		if err != nil {
			s.Log(ErrorLevel, err.Error())
			return "nok", nil
		}
		s.Log(InfoLevel, "RES: %+v", res)
		return "ok", nil
	})
	s.Serve()
}
`

**Comment by rgzr** [comment]
Hi oriolf,

_NOTICE: Sugar has been moved to its own repo (github.com/nayarsystems/sugar) right now, so we should discuss future issues there._

 ¿Which versions are you trying with?

I am trying the following example code and it works for me with:
- Version 0.1.1 of nexus
- Either latest master or development version of nxcli
- Latest master version of sugar

Running the fibsrv sugar example and the following code and doing a task push as root to "test.issue" results in a correct push to "test.sugar.fibsrv.fib" with the same connection used to pull.

```
package main
import (
    "time"
    "github.com/jaracil/ei"
    "github.com/nayarsystems/sugar"
    . "github.com/nayarsystems/sugar/log"
    nexus "github.com/jaracil/nxcli/nxcore"
)
func main() {
    s := sugar.NewService("root:root@localhost", "test", &sugar.ServiceOpts{4, time.Hour, 12, false})
    s.AddMethod("issue", func(task *nexus.Task) (interface{}, *nexus.JsonRpcErr) {
        res, err := s.GetConn().TaskPush("test.sugar.fibsrv.fib", ei.M{"v":1000, "t": 1}, time.Minute)
        if err != nil {
            s.Log(ErrorLevel, err.Error())
            return "nok", nil
        }
        s.Log(InfoLevel, "RES: %+v", res)
        return "ok", nil
    })
    s.Serve()
}
```

**Comment by oriolf** [comment]
Hi again,

Upgrading to the last version of sugar solved the problem.

Cheers

**Comment by rgzr** [comment]
Nice! I'm closing the issue ;)
